INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto )
VALUES ('2014A', '0302')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1703')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1404')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1504')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1604')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1704')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1804')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '2104')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '2204')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '2304')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '2404')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '2504')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '0105')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '0505')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('2014A', '1505')