INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto )
VALUES ('0000A', '0502')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2103')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1404')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1504')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1604')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1704')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1804')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2104')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2204')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2304')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2404')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '2504')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '0105')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '0505')
INSERT INTO calendarAsueto ( cla_ciclo, cla_fecasueto ) 
VALUES ('0000A', '1505')